spring:
  security:
    oauth2:
      client:
        registration:
          oauth.com-playground:
            clientId: t8cKx3V6oIR7u571cNrjqvx4
            clientSecret: G6o0MceOpw15E-2-xCeV0vVMaCHWxh7cSIsa4eSdx1ZENst5
            #  UserID    exuberant-lobster@example.com
            #  password  Open-Flamingo-69
          github:
            clientId: 93281264a4031c6d3db5
            clientSecret: 89901f240e3695f68186f1b76279b5096f32b3be
          google:
            clientId: 237918149568-nhmephrfct59sk1it2fucf4mv6mgsi7s.apps.googleusercontent.com
            clientSecret: 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

# ...
